- docs/resources/roadmap.md
- docs/smart-contracts/erc20-collateral-pool-contract/example.md
- docs/smart-contracts/pools-contract/introduction.md
> Updated 2024 roadmap

- .github/workflows/deploy.yml
- Resolve #issueNumber
1. first step
2. next step
> ci(releases): Create Release Notes

- docs/back-end-api/erc20CollateralToken/default.md
- docs/back-end-api/sdk/_category_.json
- docs/back-end-api/sdk/software-development-kit.md
- docs/back-end-api/software-development-kit.md
> docs(api): add content to get started with the API #75

- docs/back-end-api/erc20CollateralToken/graphql.md
- docs/back-end-api/erc20CollateralToken/restful.md
- docs/back-end-api/sdk/software-development-kit.md
- yarn.lock
> docs(pools): update attributes to update metadata

- docs/smart-contracts/pools-contract/example.md
- docs/smart-contracts/pools-contract/technical_aspects.md
> docs(pools): fix typos and reorder content #89

- README.md
- docs/resources/howto-metadata-config.md
- docs/resources/howto-pools-config.md
- docs/resources/howto-whitelableing.md
- package.json
- static/defactor-pools.json
- yarn.lock
- add onboarding docs
- add branding documentation 
- add env vars documentation
- add metadata config docs
- add JSON list of deployed instances 
- resolve #85
> Update onboarding docs

- docs/resources/how-tos/pools/project-onboarding.md
> Fix broken links

- docs/pools/back-end-api/sdk/counterparty-pool.md
> Update docusaurus version

- docs/resources/glossary.md
I have added a few terms to the glossary
> docs(glossary): update glossary to add new terms.md

- docs/pools/pools-processes/_category_.json
> Add category json for pools processes

- .github/workflows/weekly-updates.yaml
- weekly-updates-bot.py
This is a Python script that generates a weekly summary of development activities from multiple GitHub repositories. It fetches pull request details, extracts issue references, and summarizes the activities. The summary is then polished using the OpenAI API and can be posted to a Slack channel.
- Fetches pull request details from multiple repositories.
- Extracts and summarizes issue references.
- Uses OpenAI to polish the summary.
- Optionally posts the summary to a Slack channel.
> Add weekly updates script

- .gitignore
- static/defactor-pools.json
> Update JSON list of instances

- docs/pools/back-end/api/counterpartyPools/graphql.md
- docs/pools/back-end/api/erc20CollateralToken/graphql.md
- docs/pools/back-end/api/erc20CollateralToken/restful.md
- Resolve #122
- Remove endpoints that don't exist in the RESTful endpoints
- Fix Update metadata pool endpoint
- Indicate that borrow and repay endpoints in the erc20 collateral pool only support tx
> fix(pools-api-endpoints): fix pools api endpoints documentation

- static/defactor-pools.json
- static/mainnet/defactor-pools.json
- static/testnet/defactor-pools.json
```text
<url>/<testnet | mainnet>/defactor-pools.json
```
> Add landshare to JSON list of instances

- docs/resources/roadmap.md
> Update Tech Roadmap

- static/mainnet/defactor-pools.json
> Update Aurus Mainnet Domain

- docs/engage/smart-contracts/staking-contract/introduction.md
- package.json
- static/testnet/defactor-engage.json
- static/testnet/defactor-pools.json
- Resolve #128 
1. first step
2. next step
> docs(staking): create introduction page #128

- docs/resources/additional-resources.md
> Update Test Environment Links

- docs/engage/how-tos/project-onboarding.md
> Added project onboarding Engage

- static/testnet/defactor-engage.json
- Update contract address for engage testnet
> docs(engage): update contract address

- static/testnet/defactor-engage.json
- Update engage contract address
Update the contract addresses for the &quot;Amoy&quot; and &quot;Sepolia&quot; staking entries in the `defactor-engage.json` file.
The contract addresses have been updated to reflect the latest deployments on the testnet, ensuring that the staking entries point to the correct and current contracts. This change is necessary to maintain the accuracy and functionality of the staking operations within the application.
> docs(engage): update contract addresses

- docs/assets/how-tos/index.md
**Added Assets New Project Onboarding description**
Add a detailed description of the Assets New Project Onboarding process, including sections on tokenizing assets, templates, asset verification, and a comparison between ERC-20 and ERC-3643 token standards.
These changes provide comprehensive guidance for users on how to onboard new projects using the Assets platform, addressing the need for clear instructions on asset tokenization and the differences between token standards. This documentation is essential for users to understand the process and make informed decisions about which token standard to use based on their specific regulatory and operational requirements.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
> Added Assets New Project Onboarding description

- static/testnet/defactor-engage.json
- Update staking dev address
Update the staking development address in the `defactor-engage.json` file for the Sepolia network.
The change is necessary to reflect the correct staking contract address for the Sepolia network, ensuring that the application interacts with the intended smart contract. This update is crucial for maintaining the accuracy and functionality of the staking feature in the development environment.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
> chore(static): update staking dev address

- docs/engage/smart-contracts/buyback-contract/_category_.json
- docs/engage/smart-contracts/buyback-contract/introduction.md
- docs/engage/smart-contracts/staking-contract/_category_.json
- docs/engage/smart-contracts/vesting-contract/_category_.json
- docs/engage/smart-contracts/vesting-contract/introduction.md
- yarn.lock
Add sections for buyback and vesting smart contracts to the documentation and adjust the position of the staking contract in the sidebar.
These changes introduce placeholder sections for the buyback and vesting smart contracts in the documentation structure to enhance organization and facilitate future content additions. The adjustment in the sidebar positions ensures a more logical and user-friendly navigation hierarchy.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
> Add engage smart contract sections

- package-lock.json
- static/mainnet/defactor-pools.json
- static/testnet/defactor-pools.json
Add RealtyX instances to the list of deployments in both the mainnet and testnet configuration files.
These changes are necessary to include RealtyX's production and development environments in the configuration, allowing them to be accessible through the specified URLs and APIs. This ensures that the RealtyX instances are correctly set up in the ecosystem for both mainnet and testnet, aligned with the overall deployment strategy.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
> Add realtyX instances to list of deployments

- static/mainnet/defactor-pools.json
- utils/postman-to-md/package-lock.json
> Update LandShare Domain Name

- static/mainnet/defactor-pools.json
> Add SongYield Mainnet Instance

- docs/engage/how-tos/index.md
- docs/engage/how-tos/project-onboarding.md
- docs/engage/how-tos/smart-contract-config.md.md
> Add staking Contract Configuration Docs

- docs/resources/roadmap.md
> Update 2024 Roadmap milestones

- docs/introduction/open-source-guidelines.md
> fix(docs): Text is not been referenced correctly

- docs/metamaskChainConnection.md
- docs/resources/_category_.json
- docs/rwa-use-cases/_category_.json
- docs/upcomingNetworks.md
> docs(webapp): Configure metamask

- docs/engage/back-end-api/introduction.md
- docs/engage/front-end-ui/intro.md
- docs/engage/smart-contracts/introduction.md
- utils/postman-to-md/yarn.lock
> Extra navigation is not necessary

- docs/pools/how-tos/howto-pools-config.md
- docs/pools/how-tos/howto-whitelableing.md
- Update env variables for the backend and frontend
- Update the branding schema
> docs: update required pools variables
